### PR TITLE
Fix mistake in MANUAL.md

### PR DESCRIPTION
**Pull request by dotflac**

### CODE REVIEW

**Comment by slingamn** [comment]
Thanks!

There's another reference to `#channel` in that same paragraph. Could you change all three to say `#channel` instead of `#test`?

**Comment by dotflac** [comment]
All good?

**Comment by slingamn** [comment]
Thanks!

**Comment by slingamn** [comment]
I made a mistake: this pull request should have been opened against 'master', not against 'stable'. I force-pushed 'stable' back to its previous hash (e43db479ca8001e09b7aeef2fba690295aea6ca4). I will merge these commits manually into master.

**Pull request merged**
