### PR TITLE
use RWMutex to protect listeners map

### PR DESCRIPTION
**Pull request by slingamn**
This fixes a crash on rehash: `fatal error: concurrent map read and map write`. I can reproduce this crash pretty reliably with a bash loop like this:

````bash
while true; do killall -v -HUP oragono; sleep 1; done;
````

The patch is more of a draft. I was wondering if there might be some way to eliminate complexity in the code that manages listeners?

### CODE REVIEW

**Comment by DanielOaks** [comment]
Hmm, yeah I've never been especially happy with the listener code, it's just structured that way because it was the first way I came across to be able to rehash them (load the new certs into them and all).

Maybe we could isolate the complexity in a ListenerManager or similar, keep all the locks together and just access it through some function calls or similar from the server. or something like that. I like adding locks but it feels like that might be more maintainable in the future, thoughts?

**Comment by slingamn** [comment]
Hmm, that could work. I'm not sure I understand all the potential problems. In particular, do you remember what the issue was here?

https://github.com/oragono/oragono/blob/97010461f705e8cc96353eb77fdf658da87c3c91/irc/server.go#L562

**Comment by DanielOaks** [comment]
Hmm... if I remember correctly, when we rehashed a number of times in a row (i.e. send `REHASH` ten times fast), sometimes there'd be an issue where it would try to update the listener while it was already being updated or something along those lines.

It doesn't look like the best solution to that issue regardless, rather just a quick fix that seemed to prevent the issue from happening while I was testing. We'd definitely need to do some further testing as we update/rewrite it, make sure we get all the edge cases out.

**Comment by DanielOaks** [comment]
Just a note, if you wanna chat about stuff in realtime or just have general questions, feel free to pop onto the `#oragono` channel on Freenode sometime ([webchat](https://www.irccloud.com/invite?channel=%23oragono&hostname=irc.freenode.net&port=6697&ssl=1)). Always happy to help with whatever.

**Comment by slingamn** [comment]
Closing in favor of #135.

**Pull request closed without merging**
