### PR TITLE
PONG param 0 should be server name

### LINKED ISSUE #1248: PONG breaks convention, breaks Thunderbird
**breaking convention:**
- oragono (irc.hashbang.sh)
`:irc.hashbang.sh PONG asd`
- charybdis (irc.alphachat.net)
`:irc-de1.alphachat.net PONG irc-de1.alphachat.net :asd`
- inspircd (irc.tilde.chat)
`:institute.tilde.chat PONG institute.tilde.chat :asd`
- unrealircd (irc.unrealircd.org)
`:irc1.unrealircd.org PONG irc1.unrealircd.org :asd`
- ngircd (irc.w3.org)
`:public-irc.w3.org PONG public-irc.w3.org :asd`

**breaking Thunderbird:**

leads to Thunderbird constantly deciding it has lost connection to the server and should reconnect
```
21:31 < Mateon1> Just for reference, I was connected to 8 other IRC servers at the time continuously for over a day (lost connection because my internet died for a couple minutes in the evening), this is the only server I'm having problems with.
21:31 < Mateon1> Also: prpl-irc: Unhandled IRC message:
21:31 < Mateon1> @time=2020-08-25T21:30:44.054Z :irc.hashbang.sh PONG _1598391044040
21:32 <~ryan> oh can it not handle PONGs that have a prefix?
21:32 < Mateon1> I could try digging into the source
21:32 < Mateon1> But seems like it
21:34 <~ryan> maybe it has a distinction between prefixed commands and non-prefixed commands that it's having issues with
21:36 < Mateon1> Hm, should be fine with the _ prefix: https://github.com/daniel-barrows/thunderbird/blob/6b0b38cdeeb0852950f15249f1b0e77f0bbddb05/chat/protocols/irc/ircBase.jsm#L287
21:37 <~ryan> hm.
21:37 <~ryan> one second.
21:37 < Mateon1> Ah, actually I missed some earlier debug output in the noise:
21:37 < Mateon1> prpl-irc: Error running command PONG with handler RFC 2812:
21:37 < Mateon1> {"rawMessage":"@time=2020-08-25T21:30:44.054Z :irc.hashbang.sh PONG _1598391044040","command":"PONG","params":["_1598391044040"],"origin":"irc.hashbang.sh","tags":{},"source":""}
21:37 < Mateon1> pongTime is undefined
```

this will be the issue, it's checking the index 1 param for starting with `_`
https://github.com/daniel-barrows/thunderbird/blob/6b0b38cdeeb0852950f15249f1b0e77f0bbddb05/chat/protocols/irc/ircBase.jsm#L289

### PR DESCRIPTION
**Pull request by jesopo**
fix #1248

### CODE REVIEW

**Comment by slingamn** [comment]
This seems like a good patch, but it comes at an awkward time --- I don't know if I want to merge this between a release candidate and a release. I'll consider what to do here.

**Comment by slingamn** [comment]
I'll merge this in 2.4. Could you:

1. Make the `PONG` arguments just `server.name` and then `msg.Params[0]`? I think most implementations echo at most one of the PING params. (Looking at freenode: you can `PING param server.freenode.net` to ping a non-local server, but you'll get back `PONG server.freenode.net your_nickname`. Inspircd doesn't have non-local ping and just echoes back the first ping param.)
2. Squash down to one commit?

**Comment by jesopo** [comment]
(done)

**Comment by slingamn** [comment]
Looks great, I'll merge this after 2.3.0 goes out.

**Pull request merged**
