### PR TITLE
Add +M (only registered/voice can speak) chanmode.

### LINKED ISSUE #1182: options for muting unregistered users
I can see two possibilities:

1. Provide a channel mode that allows unregistered users to join, but forbids them from speaking.
    a. Pro: defers control to the channel operator (the server operator can still include the mode in `channels.default-modes`
    b. Con: uses up a mode letter (any precedents?)
2. Make it a server setting that can be modified with `CHANSERV SET`
    a. Pro: doesn't use up a mode letter
    b. Con: clunky

### PR DESCRIPTION
**Pull request by ajaspers**
Fixes #1182.

### CODE REVIEW

**Comment by slingamn** [comment]
This is great. I'm thinking of it less as an anti-spam measure, and more as a powerful nudge towards registering one's nick.

I wonder if we should start returning the relevant mode from `CanSpeak` and incorporating it into the error message?

**Comment by ajaspers** [comment]
> I wonder if we should start returning the relevant mode from `CanSpeak` and incorporating it into the error message?

Done. I modeled the error message after the one returned for +C.

**Comment by slingamn** [comment]
Excellent. Would you mind squashing the branch?

**Comment by slingamn** [comment]
Awesome.

**Pull request merged**
