### PR TITLE
implement draft/resume-0.4

### PR DESCRIPTION
**Pull request by slingamn**
The diff is more readable without whitespace. Two main ideas:

1. Resume is now implemented the same way as a reattach: the session is detached from the old client (which is subsequently destroyed because it has 0 sessions) and attached to the new one. A new goroutine is spawned for it, and the registration burst etc. are played as the first action on the new goroutine.
1. Clients are now allowed to remain online with 0 connected sessions, as long as they have the blessing of the new `client.brbTimer`, which will eventually time them out if they fail to reconnect.
1. Interaction between resume and reattach is not too complicated. A client has at most one valid resume token at any given time --- this is either the first token ever issued to the client (probably the one during initial registration), or the successor token after a chain of resumes from the original token. Any number of additional sessions are permitted. If one of those additional sessions requests `draft/resume-0.4` during registration, it will receive a resume token, but after the reattach the token will be invalid (its table entry will be deleted when its original `Client` object is destroyed after the reattach). Any attempts to resume with that token will fail --- but the client will be able to reattach as usual, without needing an alternate nick. (Probably the correct client behavior is to try the preferred nick first anyway after a failed resume, by sending CAP END, and seeing if you get it; you might get lucky!)
1. You need to either have a resume token *or* be logged in to BRB, so you can BRB from any logged-in session. You can reattach to a BRB'ed client without needing the resume token, whether or not the session that issued the BRB had a token. If you BRB and don't come back, but have other healthy sessions, the BRB timer will see them when it fires and leave the client alive.

### CODE REVIEW

**Comment by slingamn** [comment]
I implemented irctests for this (an enhancement to the existing test that covers chained resumes, and a new test for BRB), but I haven't pushed them yet since they're not backwards-compatible with the current oragono master.

**Comment by slingamn** [comment]
Since reattach (unlike resume) does not clear the BRB state, you always have at least $DURATION after your BRB to reattach, even if another session BRB'ed, reattached, and then QUIT. The tradeoff is that if you then QUIT from all your sessions while the BRB timer is still going, the QUIT doesn't register until the timer expires.

**Comment by slingamn** [comment]
Here's the `352 RPL_WHOREPLY` line, before and after this change, from a client with nick `observer` querying a client with nick `nick`, username `user`, and realname `real name`:

````
:oragono.test 352 observer * ~user 0::1 oragono.test nick H :0 real name
````

**Comment by DanielOaks** [comment]
Nothing in here that looks too bad. Thanks for the great contributions, appreciate it mate

**Pull request merged**
