### PR TITLE
frontend for persistent account modes in channels

### PR DESCRIPTION
**Pull request by slingamn**
I called it `AMODE` to emphasize the connection with accounts, as opposed to nicks. Maybe `AUMODE` would be better? Or something else entirely? The syntax looks like a `MODE` command, e.g., `/msg ChanServ AMODE #channel +h accountname`.

### CODE REVIEW

**Comment by DanielOaks** [comment]
Oooh. I really, really like the way this is implemented, and the `AMODE` command. Some changes I'd look at would be:

- Improving the display of users and modes when using a raw `AMODE #chan`. Just making it more streamlined, lil sorta-table display.
- Allowing `+o` AMODE'd users to AMODE +-o and AMODE +-h other people.

**Comment by slingamn** [comment]
I didn't add the table display in my latest commit; IMO it's not part of the "minimum viable product" for this change. I can work on it if you have strong feelings about it.

**Comment by DanielOaks** [comment]
Nice, yeah definitely don't consider it part of the minimum viable product

**Comment by DanielOaks** [comment]
I think the only thing I'd like to do is confirm the behaviour around oper/halfop/founder/etc, and once that's good I'll merge this in. Shouldn't take too long, just be over the weekend or w/e.

**Comment by DanielOaks** [comment]
Whoo, looks nice! We'll look at the formats and text as we go, thanks a bunch for this work :)

**Pull request merged**
