### PR TITLE
nickserv: implement GHOST, GROUP, DROP, and INFO

### PR DESCRIPTION
**Pull request by slingamn**
Lots of fiddly edge cases here. I should probably test this more. I thought I'd throw it at you anyway because any fixes will probably be narrow in scope.

### CODE REVIEW

**Comment by DanielOaks** [comment]
This is awesome, seriously. Great work.

I think it' be worth building up some proper tests for this functionality, as well as looking at backend oper management of all this. May wanna look at standard `OperServ` commands or something down the line for oper management of this sorta services stuff.

But that extra work can come down the line a bit. This'll be tested and merged pretty soon, thanks for throwing it up as a PR!

**Comment by slingamn** [comment]
That makes sense. Are you thinking of unit tests, or irctest integration tests?

**Comment by DanielOaks** [comment]
Hmm, probably irctest yeah.

On the subject of unit tests... would it be worth including some integration tests in the server itself, something along the lines of what Eris does [here](https://github.com/prologic/eris/blob/master/main_test.go)?

**Comment by slingamn** [comment]
I'd rather keep them in irctest.

This change has two bugs:

1. You can register a new account that has the same name as a reserved nick
1. You can reserve a nick that has the same name as a registered, but unverified, account

**Pull request merged**
