### PR TITLE
draft/resume-0.2 implementation, message history support

### PR DESCRIPTION
**Pull request by slingamn**
This got big and messy. A few notes:

1. I got worried about history replay overrunning the client's sendq, particularly in cases where the client is joined to multiple busy channels. Instead, I added an interface to do blocking writes to the client's socket, bypassing the sendq. Based on my understanding of how progress works in Oragono, this shouldn't cause any problems, because we're writing to the client's socket from the client's own goroutine, and we're not holding any locks while we do it.
1. I think we might want to add a note to the spec that servers SHOULD verify resume tokens using a constant-time string comparison function, if one is available. (Python 3.6 has [secrets.compare_digest](https://docs.python.org/3/library/secrets.html#secrets.compare_digest), and Go has [subtle.ConstantTimeCompare](https://golang.org/pkg/crypto/subtle/#ConstantTimeCompare).)
1. This needs an irctest. It also probably needs more manual testing than I've done (I just unsystematically checked a few different cases of RESUME, with different cap negotiations and different unaffected clients observing the resume.) If you have suggestions about obscure cases to check, I can check them.

### CODE REVIEW

**Comment by DanielOaks** [comment]
Loootsa changes. Looks pretty nice from a browse through. Note to self, maybe change `LIST` to use `sendInternal(true` as well so that large responses from that can't overload clients, and make sure that command is penalised more heavily in terms of fakelag than regular commands? (and add the `SAFELIST` ISUPPORT token).

**Comment by slingamn** [comment]
Pending benchmarks, we might be able to switch *all* sending of command responses to clients to use `BlockingWrite` --- keeping the asynchronous `Write` only for delivery of `PRIVMSG` and the like.

**Comment by slingamn** [comment]
(Under the current implementation, this is simplified considerably by `ResponseBuffer`, since no data is actually sent until the final call to `ResponseBuffer.Send`, which occurs while no locks are held. So we could just call `SetBlocking(true)` on all of those buffers. But that would make it impossible to do #259.)

**Comment by DanielOaks** [comment]
Overall, no worries with this implementation from the looks of it. We'll eval those additional possible changes to LIST and such going forward. Thanks for the awesome work on this mate, really appreciate the time you've put into it :)

**Pull request merged**
