### PR TITLE
Allow stdout/stderr colorization to be turned off

### PR DESCRIPTION
**Pull request by kula**
Add a new logging stanza option "colorizable", which allows you
to turn off the ANSI colorization of stdout or stderr logging
targets. Useful for running oragono under systemd with stock
journal+syslog logging - otherwise you get a lot of ANSI control
characters in your syslog.

Defaults to `true`, to retain backwards compatability.

### CODE REVIEW

**Comment by slingamn** [comment]
Thanks very much for your patch!

I discussed this with @DanielOaks and I'm leaning towards stripping out the color stuff entirely; it adds a fair amount of complexity and it's not easy to get a color scheme that displays well in all terminals.

The other option I was considering was to auto-detect whether stdout/stderr is a tty (the coloring library we use already pulls in a tty detection library, but contrary to what I had believed, doesn't actually perform this check on non-Windows platforms). Then there would be a configurable color setting as in your patch, but if the value is unset, it would default to whether stdout/stderr is a tty.

Thoughts?

**Comment by kula** [comment]
Either of those works for me. I don't want the color pretty much ever, but I also don't know who might find that useful or in what cases they might. As long as I've got a bit to flip to turn off color if there is, I'm entirely happy.

Please do give a close look at the method I used to get a default true value for the flag --- I haven't done much Go programming yet, and I think that's the general Go way of doing that, but someone with a bit more experience should give it a closer look.

**Comment by slingamn** [comment]
I'm still considering, but the more I think about it, color seems primarily useful to people developing Oragono, not to operators/users. (I have an instance I run myself and I capture the log output with systemd-journald. I had always assumed that Oragono was detecting this and stripping the color codes, but as you point out, they're actually in there and I just need [--output cat](https://serverfault.com/a/893763) if I want to see them. But now that I have them, I don't think I will find them very useful.)

The pattern you're using seems good. Mostly what I've been doing is accepting the need for a postprocessing step, rather than trying to produce the final result in a single `yaml.Unmarshal` operation. For example, this is what I do for booleans:

https://github.com/oragono/oragono/blob/33fd75ae54411c6e9020942c3804736396dc8ef6/irc/config.go#L566

https://github.com/oragono/oragono/blob/33fd75ae54411c6e9020942c3804736396dc8ef6/irc/config.go#L1035

https://github.com/oragono/oragono/blob/33fd75ae54411c6e9020942c3804736396dc8ef6/irc/utils/args.go#L86

This has strengths and weaknesses. I like it better when (as in this case) the compiler is enforcing that the raw value can't be used directly (because unlike in C or C++, pointers don't have truth values). Your solution has this property as well. (When the raw and postprocessed results have the same type, e.g., `[]string`, there's an annoying effect where the raw value has to be a public  / capitalized field, because otherwise it can't be unmarshalled at all, and conversely it's preferable [but not actually necessary] that the postprocessed value be private / lowercased, because otherwise someone could accidentally write a config file that populates it directly.)

A minor gotcha with defining custom `UnmarshalYAML` methods is that they won't be called at all if the field is not present, so it's necessary that the zero value of the type implement the desired default behavior (as it does in your case, but there are other settings where I find postprocessing more idiomatic).

Anyway, our `LoadConfig` function does a lot of very elaborate postprocessing, producing a `*Config` that is immutable after load and can be read using `atomic.LoadPointer`. This is very efficient on amd64 because the atomic load compiles down to a plain `MOV` instruction.

**Comment by slingamn** [comment]
Closing this in favor of #940.

**Pull request closed without merging**
