### PR TITLE
work around znc's broken nickserv support

### PR DESCRIPTION
**Pull request by slingamn**

### CODE REVIEW

**Comment by DanielOaks** [comment]
Any chance you have a list of the other magic strings it accepts? Just wanna see if we can make the string a touch more user-friendly at all

**Comment by DanielOaks** [comment]
Nice chasing up on this btw, great discovery

**Comment by DanielOaks** [comment]
Oh I see, code link over in the v3 issue, thanks! https://github.com/znc/znc/blob/458ce602aa8b14ab870371e26ccec9d29c77bb97/modules/nickserv.cpp#L101

**Comment by slingamn** [comment]
@jesopo found at least half of this :-)

Looks like the same set of magic strings between master and 1.6.x: https://github.com/znc/znc/blob/1c182775e675edd775aa65a6ff004d2c85cd3ad0/modules/nickserv.cpp#L94

"This is a registered nickname, please identify to NickServ within %v or change it" seems like the least bad choice on the menu. Not sure it's much better than what's in this branch though.

**Comment by DanielOaks** [comment]
What do ya' think about this message? (with $b using the ircfmt formatting characters)

    This nickname is reserved. Please login within %v (using $b/NS IDENTIFY <password>$b or SASL)

**Comment by DanielOaks** [comment]
perf

**Comment by jwheare** [comment]
When does this issue arise? If znc knows the nickserv password, wont it already be using sasl and thus never see this message? If it doesn’t have the password then there’s nothing to do anyway.

**Comment by slingamn** [comment]
ZNC <= 1.6.x has a SASL bug that causes handshakes with oragono to fail: https://github.com/znc/znc/issues/1212

This issue can be reproduced in ZNC by not configuring SASL, but instead configuring ZNC's [nickserv module](https://wiki.znc.in/Nickserv). (I think the nickserv module and the sasl module are separate in that the sasl module won't try to grab a password that was only configured for nickserv.)

**Comment by jwheare** [comment]
FYI we also use a list of magic strings for this no-sasl fallback in IRCCloud, to delay joins, but there’s a timeout in case we never see any of them:

```erlang
        "password accepted", % Nickserv
        "you are now identified", % NickServ/freenode 
        "you are now logged in", % Q/quakenet 
        "you are already logged in", % NickServ/freenode 
        "authentication successful", % X/undernet 
        "i recognize you" %AuthServ/gamesurge
```

**Comment by DanielOaks** [comment]
"you are now logged in" is a a good one

**Pull request merged**
