### PR TITLE
Added ChanServ DEOP command

### PR DESCRIPTION
**Pull request by RunBarryRun**

### CODE REVIEW

**Comment by slingamn** [comment]
You can use `git status` to check for modified or new files that have not been committed as expected.

**Comment by RunBarryRun** [comment]
Shall i delete those? sorry this is my first time using pulls :)

**Comment by slingamn** [comment]
No, this is fine, I'll probably cherry-pick the first commit (adding `CHANSERV DEOP`).

**Comment by slingamn** [comment]
I'm going to close this for now. I'll reevaluate stats for always-on clients later.

**Pull request closed without merging**
